add_newline = false
command_timeout = 3000

format = """
[{!CHAR_DIVIDER_ALT!}](fg:#282C34)\
${custom.linux}\
${custom.language}\
[{!CHAR_DIVIDER!}](fg:#282C34)\
( $git_branch)\
( $git_status)\
[ {!CHAR_DIVIDER_ALT!}](fg:#282C34)\
$directory\
[( $status)](bg:#282C34)\
[{!CHAR_DIVIDER!} ](fg:#282C34)
[[ ](){!CHAR_DIVIDER_ALT!}](fg:#282C34)\
[](bg:#282C34 fg:#E06C75)[](bg:#282C34 fg:#E5C07B)[](bg:#282C34 fg:#98C379)\
[{!CHAR_DIVIDER!}](fg:#282C34) \
"""

[directory]
style = "bg:#282C34 fg:#ABB2BF"
format = "[$path]($style)[( $read_only)]($read_only_style)"
read_only = ""
read_only_style = "bg:#282C34 fg:#E06C75"
truncation_length = 2
truncation_symbol = " "

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Trash" = " "
"Desktop" = " "
"Videos" = " "
"Templates" = " "
".config" = " "
".cache" = " "
"home" = " "
"~" = " "

[custom.linux]
os = 'linux'
when = """
$HOME/.config/starship/detectlang no
"""
command = """
$HOME/.config/starship/detectdistro
"""
style = "bg:#282C34 fg:#98C379"
format = "[$output ]($style)"

[custom.language]
when = """
$HOME/.config/starship/detectlang has
"""
command = """
$HOME/.config/starship/detectlang symbols
"""
style = "bg:#282C34 fg:#98C379"
format = "[$output ]($style)"

[git_branch]
symbol = ""
style = "bg:#282C34 fg:#61AFEF"
format = """
[{!CHAR_DIVIDER_ALT!}](fg:#282C34)\
[$symbol( $branch)]($style)\
[{!CHAR_DIVIDER!}](fg:#282C34)\
"""

[git_status]
style = "bg:#282C34 fg:#61AFEF"
format = """
[{!CHAR_DIVIDER_ALT!}](fg:#282C34)\
[$all_status$ahead_behind]($style)\
[{!CHAR_DIVIDER!}](fg:#282C34)\
"""
modified = " "
conflicted = " "
ahead = " "
behind = " "
diverged = " "
up_to_date = " "
untracked = " "
stashed = " "
renamed = " "
deleted = " "
staged = " "

[status]
disabled = false
style = "bg:#282C34 fg:#ABB2BF"
format = "[$symbol]($style)"
symbol = "[ ](bg:#282C34 fg:#E06C75)"
success_symbol = ""
not_executable_symbol = "[ ](bg:#282C34 fg:#E06C75)"
not_found_symbol = "[](bg:#282C34 fg:#CAAA6A)"
sigint_symbol = "[ ](bg:#282C34 fg:#E06C75)"
signal_symbol = "[ ](bg:#282C34 fg:#E06C75)"
map_symbol = true
